max_width = 120
error_on_line_overflow = true
error_on_unformatted = true
overflow_delimited_expr = true
newline_style = "Native"
wrap_comments = true
comment_width = 100
format_strings = false
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
reorder_imports = true
reorder_modules = true
reorder_impl_items = true
use_field_init_shorthand = true
condense_wildcard_suffixes = true